### PR TITLE
fix(composer): refactor executor logic and initialize nonce when pinging sequencer

### LINKED ISSUE #292: composer: separate bundle construction from sequencer transaction building
Currently, rollup transactions are serialized and turned into a `Vec<Action>` in the [same function](https://github.com/astriaorg/astria/blob/main/crates/astria-composer/src/searcher/mod.rs#L209) that nonce is attached to create an `Unsigned`.

This creates a problem when transactions fail to be submitted due to incorrect nonce. While transaction failures due to incorrect nonce are not currently handled, separating these two functionalities will make the change much simpler in the future.

Instead of simply fetching a new nonce and attaching it to the `Vec<Action>` in [`handle_pending_tx`](https://github.com/astriaorg/astria/blob/main/crates/astria-composer/src/searcher/mod.rs#L209) do the following:

1. Move nonce and signing logic out from `handle_pending_txs`
    1a. Rename `handle_pending_txs` to `bundle_pending_txs` to clarify what it is doing.
    1b. Output a `Vec<Action>` to separate the interaction with the sequencer from bundle construction
2. Create an `Executor` struct that handles sequencer interaction
    2a. Run `wait_for_sequencer` in the `Executor`'s `run_until_stopped` function
    2b. For each `Vec<Action` do the following:
        - Retrieve nonce to create an `Unsigned`
        - Sign `Unsigned` to create a `Signed` tx
        - Submit `Signed` tx to sequencer.
3. Instead of running [`handle_signed_tx`](https://github.com/astriaorg/astria/blob/main/crates/astria-composer/src/searcher/mod.rs#L239) tasks in the `Searcher` object, pass the `Vec<Action>` to the `Executor` via a channel.

### PR DESCRIPTION
**Pull request by itamarreif**
## Summary

This is the first PR out of 3 to address nonce management in the Composer. This one specifically implements #292 and #252. A PR implementing #293 will follow and depend on this one.

## Background

Currently, sequencer transactions that fail due to invalid nonce are not handled, resulting in rollup transactions.

## Changes
(from #292 )

- [x] Move nonce and signing logic out from handle_pending_txs
  - [x] Rename handle_pending_txs to bundle_pending_txs to clarify what it is doing.
  - [x] Output a Vec<Action> to separate the interaction with the sequencer from bundle construction
- [x] Create an Executor struct that handles sequencer interaction
  - [x] Run wait_for_sequencer in the Executor's run_until_stopped function
  - [x] For each Vec<Action do the following:
    - Retrieve nonce to create an Unsigned
    - Sign Unsigned to create a Signed tx
    - Submit Signed tx to sequencer.
- [x] Instead of running [handle_signed_tx](https://github.com/astriaorg/astria/blob/main/crates/astria-composer/src/searcher/mod.rs#L239) tasks in the Searcher object, pass the Vec<Action> to the Executor via a channel.

(from #252)
- [x] Initialize `Executor`'s nonce in `Executor::wait_for_sequencer()`

(minor cleanup)
- [x] Change naming in `Collector` to reflect that the implementation is Geth-specific, rather than generic over EVM clients (due to dependency on websockets endpoint).

## Testing

- [x] Updated the existing tests to also verify the nonce is initialized properly.

## Related Issues

closes #292, #252

### CODE REVIEW

File: crates/astria-composer/src/searcher/collector.rs [hunk 1]
```diff
@@ -213,12 +213,11 @@ impl Collector {
 /// TODO(https://github.com/astriaorg/astria/issues/216): add timeouts for
 /// `subscribe_full_pendings_txs` (more complex because it's a stream).
 #[derive(Clone, Debug)]
-struct EthClient {
+struct GethClient {
```
Comment (noot) [inline crates/astria-composer/src/searcher/collector.rs:216]: why is this geth now? what geth-specific functionality are we using?

File: crates/astria-composer/src/searcher/executor.rs [hunk 2]
```diff
@@ -0,0 +1,321 @@
...
+
+use crate::Config;
+
+pub(super) type StatusReceiver = watch::Receiver<Status>;
+pub(super) type Sender = mpsc::Sender<Vec<Action>>;
+
+pub(super) fn spawn(cfg: &Config) -> eyre::Result<(Sender, StatusReceiver)> {
+    info!("Spawning Executor subtask for Searcher");
+    // create channel for sending bundles to executor
+    let (executor_tx, executor_rx) = mpsc::channel(256);
```
Comment (noot) [inline crates/astria-composer/src/searcher/executor.rs:55]: why 256?

File: crates/astria-composer/src/searcher/executor.rs [hunk 3]
```diff
@@ -0,0 +1,321 @@
...
+            .map_err(|_| eyre!("invalid private key length; must be 32 bytes"))?;
+        let sequencer_key =
+            SigningKey::try_from(private_key_bytes).wrap_err("failed to parse sequencer key")?;
+        private_key_bytes.zeroize();
+
+        // create address from signing key
+        let sequencer_address = Address::from_verification_key(sequencer_key.verification_key());
+
+        // create channel for status reporting
+        let (status, _) = watch::channel(Status::new());
```
Comment (noot) [inline crates/astria-composer/src/searcher/executor.rs:152]: where's the receiver? the receiver has to be used otherwise sending on this channel will error due to all receivers being dropped

File: crates/astria-composer/src/searcher/executor.rs [hunk 4]
```diff
@@ -0,0 +1,321 @@
...
+        self.status.subscribe()
+    }
+
+    /// Return the current nonce
+    fn nonce(&self) -> u32 {
+        self.nonce.load(Ordering::Relaxed)
+    }
+
+    /// Gets the next nonce to sign over
+    fn get_next_nonce(&mut self) -> u32 {
```
Comment (noot) [inline crates/astria-composer/src/searcher/executor.rs:175]: name this something like `get_and_increment_nonce` - bad to have a function called `get` that actually mutates stuff

File: crates/astria-composer/src/searcher/executor.rs [hunk 5]
```diff
@@ -0,0 +1,321 @@
...
+        // get current nonce and calculate next one
+        let curr_nonce = self.nonce();
+        let next_nonce = curr_nonce + 1;
+        // save next nonce
+        self.nonce.store(next_nonce, Ordering::Relaxed);
+        curr_nonce
```
Comment (noot) [inline crates/astria-composer/src/searcher/executor.rs:181]: replace this with `fetch_add`: https://doc.rust-lang.org/stable/std/sync/atomic/struct.AtomicU32.html#method.fetch_add

```suggestion
self.nonce.fetch_add(1, Ordering::Relaxed)
```

File: crates/astria-composer/src/searcher/executor.rs [hunk 6]
```diff
@@ -0,0 +1,321 @@
...
+    }
+
+    /// Creates an `Unsigned` from `Vec<Action>` using the current nonce.
+    /// If the current nonce is not stored, fetches the latest nonce from the sequencer node.
```
Comment (noot) [inline crates/astria-composer/src/searcher/executor.rs:185]: is the nonce ever not stored?

File: crates/astria-composer/src/searcher/executor.rs [hunk 7]
```diff
@@ -0,0 +1,321 @@
...
+    fn make_unsigned_tx(&mut self, actions: Vec<Action>) -> UnsignedTransaction {
+        // get current nonce and increment nonce
+        let curr_nonce = self.get_next_nonce();
+        UnsignedTransaction {
+            nonce: curr_nonce,
+            actions,
+        }
+    }
+
+    /// TODO
```
Comment (noot) [inline crates/astria-composer/src/searcher/executor.rs:195]: is this done?

File: crates/astria-composer/src/searcher/executor.rs [hunk 8]
```diff
@@ -0,0 +1,321 @@
...
+
+        // for each bundle received, create unsigned tx, sign tx, then submit tx
+        // Vec<Action> -> Unsigned -> Signed -> Submit
+        while let Some(bundle) = self.executor_rx.recv().await {
+            // create unsigned tx
+            let unsigned_tx = self.make_unsigned_tx(bundle);
+            // sign tx
+            let signed_tx = unsigned_tx.into_signed(&self.sequencer_key);
+            // submit tx
+            self.submit_tx(signed_tx).await?;
```
Comment (noot) [inline crates/astria-composer/src/searcher/executor.rs:231]: this will shut down the loop if there's an error, is that what we want?

File: crates/astria-composer/src/searcher/collector.rs (hunk 1 above)
Comment (itamarreif) [reply crates/astria-composer/src/searcher/collector.rs:216]: it depends on the websockets endpoint, which is geth specific. nothing changed, just renaming for clarity

File: crates/astria-composer/src/searcher/executor.rs (hunk 7 above)
Comment (itamarreif) [reply crates/astria-composer/src/searcher/executor.rs:195]: my bad, forgot to update comment

File: crates/astria-composer/src/searcher/executor.rs [hunk 9]
```diff
@@ -0,0 +1,333 @@
...
+    error,
+    info,
+    instrument,
+    warn,
+};
+
+use crate::Config;
+
+pub(super) type StatusReceiver = watch::Receiver<Status>;
+pub(super) type Sender = mpsc::Sender<Vec<Action>>;
```
Comment (dereksione) [inline crates/astria-composer/src/searcher/executor.rs:41]: Would prefer a more specific name for this - `Sender` is too generic - would prefer a `Vec<Action>` be renamed to something like  a `bundle` (just for ex.) and this to be `BundleSender`

File: crates/astria-composer/src/searcher/executor.rs [hunk 10]
```diff
@@ -0,0 +1,333 @@
...
+                error!("executor task exited unexpectedly");
+            }
+            Ok(Err(e)) => {
+                error!(
+                    error.message = %e,
+                    error.cause_chain = ?e,
+                    "executor task failed unexpectedly with error",
+                );
+            }
+            Err(e) => {
```
Comment (dereksione) [inline crates/astria-composer/src/searcher/executor.rs:68]: I feel like this case and the case above can be combined. If there is meaningful distinction between the two, they don't seemed to be clear from how the branches are handled

File: crates/astria-composer/src/searcher/mod.rs [hunk 11]
```diff
@@ -376,48 +270,27 @@ impl Searcher {
...
-            let client = self.sequencer_client.clone();
-            async move { client.abci_info().await }
-        })
-        .retry(&backoff)
-        .notify(|err, dur| warn!(error.msg = %err, retry_in = %format_duration(dur), "failed getting abci info; retrying"))
+    async fn wait_for_executor(&self) -> eyre::Result<()> {
+        // wait to receive executor status
+        let mut status = self.executor_status.clone();
+        async move {
+            match status.wait_for(executor::Status::is_connected).await {
```
Comment (dereksione) [inline crates/astria-composer/src/searcher/mod.rs:277]: I don't think we need a match statement for this - just upwards propagate the error and then return and `Ok(())`

File: crates/astria-composer/src/searcher/executor.rs (hunk 10 above)
Comment (itamarreif) [reply crates/astria-composer/src/searcher/executor.rs:68]: They are for handling different errors. This one is for the executor task panicking and the other is for it returning an error - since they're different code paths I feel like they should be reported differently.

File: crates/astria-composer/src/searcher/executor.rs (hunk 9 above)
Comment (itamarreif) [reply crates/astria-composer/src/searcher/executor.rs:41]: this follows the naming scheme used in the conductor: https://github.com/astriaorg/astria/blob/937f710d23cdde80a2768309f12105d46e55129b/crates/astria-conductor/src/executor.rs#L45

externally to this module this appears as `executor::Sender`

**Review by SuperFluffy — COMMENTED** [review]
I realize I never submitted by review

File: crates/astria-composer/src/searcher/executor.rs [hunk 12]
```diff
@@ -0,0 +1,322 @@
...
+    debug,
+    error,
+    info,
+    instrument,
+    warn,
+};
+
+use crate::Config;
+
+pub(super) type StatusReceiver = watch::Receiver<Status>;
```
[the remark this answers is not in the document]
Comment (itamarreif) [reply crates/astria-composer/src/searcher/executor.rs:42]: just matching the conductor: https://github.com/astriaorg/astria/blob/937f710d23cdde80a2768309f12105d46e55129b/crates/astria-conductor/src/executor.rs#L45

File: crates/astria-composer/src/searcher/executor.rs (hunk 9 above)
Comment (SuperFluffy) [reply crates/astria-composer/src/searcher/executor.rs:43]: Type aliases should be uses sparsely and only when they improve code clarity. A good example is `type Result<T> = Result<T, CrateSpecificError>`. For things like `Sender<ExecutorCommand>` they don't really improve clarify because a) this type is only used in 2 or so places, and b) I have to look up the alias to understand what's inside. The overhead isn't worth it. We should change conductor accordingly.

File: crates/astria-composer/src/searcher/executor.rs [hunk 13]
```diff
@@ -0,0 +1,322 @@
...
+    status: watch::Sender<Status>,
+    // Channel for receving bundles to pack, sign, and submit
+    executor_rx: mpsc::Receiver<Vec<Action>>,
+    // The client for submitting wrapped and signed pending eth transactions to the astria
+    // sequencer.
+    sequencer_client: SequencerClient,
+    // Private key used to sign sequencer transactions
+    sequencer_key: SigningKey,
+    // Nonce of the sequencer account we sign with
+    nonce: Arc<AtomicU32>,
```
[the remark this answers is not in the document]
Comment (itamarreif) [reply crates/astria-composer/src/searcher/executor.rs]: my bad, this was a relic of how multiple txs were submitted in parallel previously. fixed.

File: crates/astria-composer/src/searcher/mod.rs [hunk 14]
```diff
@@ -226,6 +245,39 @@ impl Searcher {
         }
     }
 
+    fn spawn_executor(&mut self) -> tokio::task::JoinHandle<()> {
+        // spawn executor task
+        let handle = tokio::spawn(
```
Comment (dereksione) [inline crates/astria-composer/src/searcher/mod.rs:250]: Nit: would prefer to be consistent between `tokio::spawn` or `tokio::task::spawn` and not use both

**Review by dereksione — APPROVED** [review]

File: crates/astria-composer/src/searcher/mod.rs (hunk 14 above)
Comment (itamarreif) [reply crates/astria-composer/src/searcher/mod.rs:250]: good catch - thanks

File: crates/astria-composer/src/searcher/collector.rs
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/collector.rs:1]: Generally fine with the naming changes, but they technically have nothing to do with the described objective of the PR. Please try to keep orthogonal changes in their own PRs.

File: crates/astria-composer/src/searcher/mod.rs [hunk 15]
```diff
@@ -45,30 +20,29 @@ use tokio::{
...
 use tracing::{
-    debug,
-    instrument,
+    error,
     warn,
 };
 
-use crate::Config;
+use crate::{
+    searcher::executor::Executor,
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:28]: executor is a submodule of searcher. Import it with `use executor::Executor`

File: crates/astria-composer/src/searcher/mod.rs [hunk 16]
```diff
@@ -45,30 +20,29 @@ use tokio::{
...
+    Config,
+};
 
 mod collector;
+mod executor;
 mod rollup;
 
 use collector::Collector;
 
+const BUNDLE_CHANNEL_SIZE: usize = 256;
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:38]: Why define a const here that's used in one place?

File: crates/astria-composer/src/searcher/mod.rs [hunk 17]
```diff
@@ -181,31 +133,26 @@ impl Searcher {
...
-        // create signing key for sequencer txs
-        let mut private_key_bytes: [u8; 32] = hex::decode(cfg.private_key.expose_secret())
-            .wrap_err("failed to decode private key bytes from hex string")?
-            .try_into()
-            .map_err(|_| eyre!("invalid private key length; must be 32 bytes"))?;
-        let sequencer_key =
-            SigningKey::try_from(private_key_bytes).wrap_err("failed to parse sequencer key")?;
-        private_key_bytes.zeroize();
+        // create channel for sending bundles to executor
+        let (executor_tx, executor_rx) = mpsc::channel(BUNDLE_CHANNEL_SIZE);
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:139]: IMO remove the const here, just put the number here.

File: crates/astria-composer/src/searcher/mod.rs [hunk 18]
```diff
@@ -216,83 +163,47 @@ impl Searcher {
...
         } = tx;
 
-        let sequencer_key = self.sequencer_key.clone();
-        let nonce = self.sequencer_nonce.clone();
-
+        // rollup transaction data serialization is a heavy compute task, so it is spawned
+        // on tokio's blocking threadpool
         self.conversion_tasks.spawn_blocking(move || {
-            // Pack into sequencer tx
+            // Pack into a vector of sequencer actions
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:175]: IMO remove comment. Kinda self evident

File: crates/astria-composer/src/searcher/mod.rs [hunk 19]
```diff
@@ -316,6 +227,8 @@ impl Searcher {
                         ),
                     }
                 }
+
+                _ = &mut exectuor_handle => { todo!("handle executor failure"); }
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:231]: Please fix this

File: crates/astria-composer/src/searcher/mod.rs [hunk 20]
```diff
@@ -216,83 +163,47 @@ impl Searcher {
...
                 // serialize and sign sequencer tx for incoming pending rollup txs
-                Some(rollup_tx) = self.new_transactions.recv() => self.handle_pending_tx(rollup_tx),
+                Some(rollup_tx) = self.new_transactions.recv() => self.bundle_pending_tx(rollup_tx),
 
                 // submit signed sequencer txs to sequencer
                 Some(join_result) = self.conversion_tasks.join_next(), if !self.conversion_tasks.is_empty() => {
                     match join_result {
-                        Ok(Ok(signed_tx)) => self.handle_signed_tx(signed_tx),
-                        Ok(Err(e)) => warn!(error.message = %e, error.cause_chain = ?e, "failed to sign sequencer transaction"),
+                        Ok(actions) => self.executor_tx.send(actions).await?,
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:206]: This is a) breaking the loop, but also b) not adding error context. Is that intentional

File: crates/astria-composer/src/searcher/mod.rs [hunk 21]
```diff
@@ -332,6 +245,39 @@ impl Searcher {
         }
     }
 
+    fn spawn_executor(&mut self) -> tokio::task::JoinHandle<()> {
+        // spawn executor task
+        let handle = tokio::task::spawn(
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:250]: This should be done directly inside `searcher::run`

File: crates/astria-composer/src/searcher/mod.rs [hunk 22]
```diff
@@ -332,6 +245,39 @@ impl Searcher {
         }
     }
 
+    fn spawn_executor(&mut self) -> tokio::task::JoinHandle<()> {
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:248]: Remove

File: crates/astria-composer/src/searcher/mod.rs [hunk 23]
```diff
@@ -332,6 +245,39 @@ impl Searcher {
...
+        // spawn executor task
+        let handle = tokio::task::spawn(
+            self.executor
+                .take()
+                .expect("executor should only be run once")
+                .run_until_stopped(),
+        );
+
+        // return handle to task that logs why executor exits
+        tokio::task::spawn(async move {
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:258]: Don't spawn a second task here

**Review by SuperFluffy — CHANGES_REQUESTED** [review]
Please address the `todo!()` macro: the `spawn` method can be removed - just spawn directly inside the searcher and await the handle. If the handle returns early, shut down searcher

File: crates/astria-composer/src/searcher/executor.rs [hunk 24]
```diff
@@ -0,0 +1,296 @@
...
+                // FIXME: currently this will fail both when there is an issue with the nonce and
+                // when unable to reach the sequencer. As there is currently no error returned by
+                // the sequencer for invalid nonces, there is nothing to handle. This should be
+                // changed after #364 is merged in a followup PR to handle nonce failues.
+                error!(
+                    error.message = %e,
+                    error.cause_chain = ?e,
+                    "failed submitting the bundle to the sequencer; bailing",
+                );
+                break;
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/executor.rs:190]: Note that I added this. Upon further inspection some of the errors are critical,  preventing the service from going on.

File: crates/astria-composer/src/searcher/executor.rs [hunk 25]
```diff
@@ -0,0 +1,299 @@
...
+            .wrap_err("failed retrieving initial nonce from sequencer")?;
+
+        while let Some(bundle) = self.executor_rx.recv().await {
+            if let Err(e) = self.process_bundle(bundle.clone()).await {
+                // FIXME: currently this will fail both when there is an issue with the nonce and
+                // when unable to reach the sequencer. As there is currently no error returned by
+                // the sequencer for invalid nonces, there is nothing to handle. This should be
+                // changed after #364 is merged in a followup PR to handle nonce failues.
+                error!(
+                    error.message = %e,
```
[the remark this answers is not in the document]
Comment (SuperFluffy) [reply crates/astria-composer/src/searcher/executor.rs:186]: Added a break statement below

**Review by SuperFluffy — APPROVED** [review]
Pushed the changes I requested after syncing with @itamarreif

File: crates/astria-composer/src/searcher/mod.rs (hunk 17 above)
Comment (itamarreif) [reply crates/astria-composer/src/searcher/mod.rs]: https://github.com/astriaorg/astria/pull/294#discussion_r1323202939

File: crates/astria-composer/src/searcher/executor.rs [hunk 26]
```diff
@@ -0,0 +1,296 @@
...
+        })
+        .retry(&backoff)
+        .notify(|err, dur|
+            warn!(error.msg = %err, retry_in = %format_duration(dur), "failed getting nonce for {:?}; retrying", self.address))
+        .await
+        .wrap_err(
+            "failed to retrieve initial nonce from sequencer after several retries",
+        )?;
+
+        // update stored nonce
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/executor.rs:240]: can we remove this obvious comments? :)

File: crates/astria-composer/src/searcher/executor.rs [hunk 27]
```diff
@@ -0,0 +1,296 @@
...
+        self.nonce = Some(nonce_response.nonce);
+        info!(
+            nonce_response.nonce,
+            "retrieved initial nonce from sequencer successfully"
+        );
+
+        // update status to connected
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/executor.rs:247]: same

File: crates/astria-composer/src/searcher/mod.rs (hunk 11 above)
Comment (SuperFluffy) [reply crates/astria-composer/src/searcher/mod.rs:308]: This was extracted from waiting for the collectors. I think (but am not sure) that it was necessary to do it there explicitly to avoid any sort of implicit `+ 'a` bound being added to the returned future.

I agree that in this case the entire `async move` is probably not necessary

File: crates/astria-composer/src/searcher/mod.rs [hunk 28]
```diff
@@ -181,32 +127,26 @@ impl Searcher {
...
 
-        // create signing key for sequencer txs
-        let mut private_key_bytes: [u8; 32] = hex::decode(cfg.private_key.expose_secret())
-            .wrap_err("failed to decode private key bytes from hex string")?
-            .try_into()
-            .map_err(|_| eyre!("invalid private key length; must be 32 bytes"))?;
-        let sequencer_key =
-            SigningKey::try_from(private_key_bytes).wrap_err("failed to parse sequencer key")?;
-        private_key_bytes.zeroize();
+        // create channel for sending bundles to executor
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:132]: obvious comments are obvious :)

File: crates/astria-composer/src/searcher/mod.rs [hunk 29]
```diff
@@ -181,32 +127,26 @@ impl Searcher {
...
+        let (executor_tx, executor_rx) = mpsc::channel(256);
+        let executor = Executor::new(&cfg.sequencer_url, &cfg.private_key, executor_rx)
+            .wrap_err("executor construction from config failed")?;
+
+        // create channel for receiving executor status
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:137]: please rm

File: crates/astria-composer/src/searcher/mod.rs [hunk 30]
```diff
@@ -216,111 +156,96 @@ impl Searcher {
...
-            let curr_nonce = nonce.fetch_add(1, Ordering::Relaxed);
-            let unsigned_tx = UnsignedTransaction {
-                nonce: curr_nonce,
-                actions: vec![Action::Sequence(SequenceAction {
-                    chain_id: chain_id.into_bytes(),
-                    data,
-                })],
-            };
-            Ok(unsigned_tx.into_signed(&sequencer_key))
+            vec![seq_action]
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:175]: creating a single-item vec seems extreme?

File: crates/astria-composer/src/searcher/mod.rs [hunk 31]
```diff
@@ -216,111 +156,96 @@ impl Searcher {
...
             chain_id,
             inner: rollup_tx,
         } = tx;
 
-        let sequencer_key = self.sequencer_key.clone();
-        let nonce = self.sequencer_nonce.clone();
-
+        // rollup transaction data serialization is a heavy compute task, so it is spawned
+        // on tokio's blocking threadpool
         self.conversion_tasks.spawn_blocking(move || {
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:167]: I believe this is no longer necessary

File: crates/astria-composer/src/searcher/mod.rs [hunk 32]
```diff
@@ -216,111 +156,96 @@ impl Searcher {
...
                 // serialize and sign sequencer tx for incoming pending rollup txs
-                Some(rollup_tx) = self.new_transactions.recv() => self.handle_pending_tx(rollup_tx),
+                Some(rollup_tx) = self.new_transactions.recv() => self.bundle_pending_tx(rollup_tx),
 
                 // submit signed sequencer txs to sequencer
                 Some(join_result) = self.conversion_tasks.join_next(), if !self.conversion_tasks.is_empty() => {
                     match join_result {
-                        Ok(Ok(signed_tx)) => self.handle_signed_tx(signed_tx),
-                        Ok(Err(e)) => warn!(error.message = %e, error.cause_chain = ?e, "failed to sign sequencer transaction"),
+                        Ok(bundle) => self.handle_bundle_execution(bundle).await,
```
Comment (SuperFluffy) [inline crates/astria-composer/src/searcher/mod.rs:215]: This now effectively blocks the entire loop

File: crates/astria-composer/src/searcher/mod.rs (hunk 30 above)
Comment (itamarreif) [reply crates/astria-composer/src/searcher/mod.rs:175]: the payload of a sequencer transaction is a vector of actions. can make the vector here or in the executor, but doing so here is more correct since the executor should just receive a payload rather than construct it.

File: crates/astria-composer/src/searcher/mod.rs (hunk 31 above)
Comment (itamarreif) [reply crates/astria-composer/src/searcher/mod.rs:167]: i disagree - since collectors are ingesting transactions concurrrently there is no reason serialization shouldnt happen concurrently. this will eventually need to be fixed, see issue #409 for an in-depth explanation.

File: crates/astria-composer/src/searcher/mod.rs (hunk 32 above)
Comment (itamarreif) [reply crates/astria-composer/src/searcher/mod.rs:217]: see #409
