### PR TITLE
fix(cli, bridge-withdrawer): dont fail entire block due to bad withdraw event

### LINKED ISSUE #1251: Bridge withdrawer shouldnt panic on bad single withdrawal address
The bridge withdrawer currently panics and stops running if there is an executed withdrawal with a bad astria address in its memo. This means the withdrawer will always panic when trying to execute the block with the bad withdrawal. Instead, we need to simply  drop the withdrawal that fails the address deserialization and continue with the next event.

### PR DESCRIPTION
**Pull request by itamarreif**
## Summary
Brief summary of the changes made, ie "what?"

## Background
Brief background on why these changes were made, ie "why?"

## Changes
- Separate the errors for getting logs from the conversion errors
- Conversion returns a `Result<Vec<Result<Action, WithdrawalConversionError>>, GetWithdrawalLogsError> ` instead of `Result<Vec<Action>, GetWithdrawalActionsError>`
- Handle failed conversions in the cli and withdrawer crates

## Testing
- Unit tests for the conversions will be added in a subsequent PR: 

## Breaking Changelist
- This fixes the bug described in #1251, where a single withdrawal which fails to be converted to an action will cause the entire rollup block's batch of withdrawals to fail, causing the withdrawer to be stuck.

## Related Issues

closes #1251

### CODE REVIEW

**Review by joroshiba — COMMENTED** [review]
LGTM

File: crates/astria-bridge-contracts/src/lib.rs [hunk 1]
```diff
@@ -353,47 +353,61 @@ where
...
+    /// - If the log cannot be decoded as a sequencer withdrawal event.
+    /// - If the log does not contain a `recipient` field.
+    /// - If the memo cannot be encoded to json.
+    /// - If calculating the amount using the asset withdrawal divisor overflows.
+    ///
+    /// # Panics
+    /// - If getting a withdrawal event type that it was not configured for. For example, if the
+    ///   configuration was specified to only get sequencer withdrawal events but an ICS20
+    ///   withdrawal is received.
+    pub fn log_to_ics20_withdrawal_action(
```
Comment (SuperFluffy) [inline crates/astria-bridge-contracts/src/lib.rs:386]: I don't see why this needs to be a pub method? I don't think it's used anywhere outside this lib? You can then also remove the doc comment.

File: crates/astria-bridge-contracts/src/lib.rs [hunk 2]
```diff
@@ -467,54 +495,97 @@ where
...
 
-impl GetWithdrawalActionsError {
+impl GetWithdrawalLogsError {
+    fn get_logs(source: GetLogsError) -> Self {
+        Self(GetWithdrawalLogsErrorKind::GetLogs(source))
+    }
+}
+
+#[derive(Debug, thiserror::Error)]
+enum GetWithdrawalLogsErrorKind {
```
Comment (SuperFluffy) [inline crates/astria-bridge-contracts/src/lib.rs:507]: Making this an enum seems unnecessary?

File: crates/astria-bridge-contracts/src/lib.rs [hunk 3]
```diff
@@ -467,54 +495,97 @@ where
 
 #[derive(Debug, thiserror::Error)]
 #[error(transparent)]
-pub struct GetWithdrawalActionsError(GetWithdrawalActionsErrorKind);
+pub struct GetWithdrawalLogsError(GetWithdrawalLogsErrorKind);
```
Comment (SuperFluffy) [inline crates/astria-bridge-contracts/src/lib.rs:498]: I think you are leaking concepts that don't appear at the high level. Please change this back.

File: crates/astria-bridge-contracts/src/lib.rs [hunk 4]
```diff
@@ -424,34 +438,48 @@ where
...
+    /// - If the log does not contain a transaction hash.
+    /// - If the log cannot be decoded as a sequencer withdrawal event.
+    /// - If the log does not contain a `recipient` field.
+    /// - If the memo cannot be encoded to json.
+    /// - If calculating the amount using the asset withdrawal divisor overflows.
+    ///
+    /// # Panics
+    /// - If getting a withdrawal event type that it was not configured for. For example, if the
+    ///   configuration was specified to only get sequencer withdrawal events but an ICS20
+    ///   withdrawal is received.
```
Comment (SuperFluffy) [inline crates/astria-bridge-contracts/src/lib.rs:454]: Remove this doc comment.

File: crates/astria-cli/src/commands/bridge/collect.rs [hunk 5]
```diff
@@ -199,10 +199,21 @@ async fn block_to_actions(
         .await
         .wrap_err_with(|| {
             format!(
-                "failed getting actions for block; block hash: `{block_hash}`, block height: \
+                "failed getting logs for block; block hash: `{block_hash}`, block height: \
```
Comment (SuperFluffy) [inline crates/astria-cli/src/commands/bridge/collect.rs:202]: This is not correct. The `actions_fetcher` is promising to give you actions. Why is this talking about logs? That's confusing.

File: crates/astria-cli/src/commands/bridge/collect.rs [hunk 6]
```diff
@@ -199,10 +199,21 @@ async fn block_to_actions(
...
                  `{rollup_height}`"
             )
-        })?;
+        })?
+        .into_iter()
+        .filter_map(|r| {
```
Comment (SuperFluffy) [inline crates/astria-cli/src/commands/bridge/collect.rs:207]: I am ambivalent about changing this logic in the CLI at this point. I am fine with adding a flag that filters out bad actions, but I would leave this to a followup.

**Review by SuperFluffy — CHANGES_REQUESTED** [review]
This PR contains a lot of renames that I don't think are necessary (and partially confusing, talking about "logs" where "actions" are promised).

File: crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/watcher.rs [hunk 7]
```diff
@@ -348,10 +351,21 @@ async fn get_and_forward_block_events(
...
         .get_for_block_hash(block_hash)
         .await
-        .wrap_err("failed getting actions for block")?;
+        .wrap_err("failed getting actions for block")?
+        .into_iter()
+        .filter_map(|r| {
+            r.map_err(|e| {
+                warn!(
+                    error = &e as &dyn std::error::Error,
+                    "failed to convert withdrawal event to sequecner action"
```
Comment (SuperFluffy) [inline crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/watcher.rs:363]:
```suggestion
                    "failed to convert rollup withdrawal event to sequencer action; dropping"
```

File: crates/astria-cli/src/commands/bridge/collect.rs [hunk 8]
```diff
@@ -202,7 +202,10 @@ async fn block_to_actions(
                 "failed getting actions for block; block hash: `{block_hash}`, block height: \
                  `{rollup_height}`"
             )
-        })?;
+        })?
+        .into_iter()
+        .collect::<Result<_, _>>()?;
```
Comment (SuperFluffy) [inline crates/astria-cli/src/commands/bridge/collect.rs:207]: Not the most efficient, but I guess it doesn't matter in this case.

File: crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/watcher.rs [hunk 9]
```diff
@@ -348,10 +351,21 @@ async fn get_and_forward_block_events(
...
+    let actions: Vec<Action> = actions_fetcher
         .get_for_block_hash(block_hash)
         .await
-        .wrap_err("failed getting actions for block")?;
+        .wrap_err("failed getting actions for block")?
+        .into_iter()
+        .filter_map(|r| {
+            r.map_err(|e| {
+                warn!(
+                    error = &e as &dyn std::error::Error,
```
Comment (SuperFluffy) [inline crates/astria-bridge-withdrawer/src/bridge_withdrawer/ethereum/watcher.rs:362]: Use our error encoding here:
```suggestion
                    error = %eyre::Report::new(error),
```

**Review by SuperFluffy — APPROVED** [review]
Nice, this is a much neater change. Thank you!

The message in the error event looks a bit wonky. See my suggestion.
