### PR TITLE
chore(composer): fix flaky test

### LINKED ISSUE #2041: composer: `two_rollup_data_submissions_single_bundle` test is flaky
The test `composer::executor::two_rollup_data_submissions_single_bundle` is flaky for me locally, with the following output:

```text
thread 'executor::two_rollup_data_submissions_single_bundle' panicked at crates/astria-composer/tests/blackbox/executor.rs:166:6:
called `Result::unwrap()` on an `Err` value: Elapsed(())
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    executor::two_rollup_data_submissions_single_bundle
```

### PR DESCRIPTION
**Pull request by ethanoroshiba**
## Summary
Fixed flaky test `composer::executor::two_rollup_data_submissions_single_bundle`.

## Background
This test previously failed semi-frequently for me locally. The issue first stemmed from the submission timeout period elapsing, but after increasing the time to span multiple blocks, it appeared that the submissions were ending up in different transactions. This seemed that it was likely due to the block timer ticking in between when the two submissions were made. As such, spinning them up concurrently appears to fix the problem.

## Changes
- Change rollup transaction submission to be concurrent as opposed to in series to avoid the block timer ticking in between submissions.

## Testing
No failures after testing >100 times.

## Changelogs
No updates required.

## Related Issues
closes #2041

### CODE REVIEW

File: crates/astria-composer/tests/blackbox/executor.rs [hunk 1]
```diff
@@ -137,33 +138,42 @@ async fn two_rollup_data_submissions_single_bundle() {
         fee_asset: "nria".parse().unwrap(),
     };
 
+    let submit_fut_1 = {
```
Comment (joroshiba) [inline crates/astria-composer/tests/blackbox/executor.rs:141]: I think it would be good to have a comment here on why we need to have the two separate futures.

**Review by joroshiba — APPROVED** [review]
Approved, but can we get a comment in here that explains why the futures are needed?

File: crates/astria-composer/tests/blackbox/executor.rs (hunk 1 above)
Comment (ethanoroshiba) [reply crates/astria-composer/tests/blackbox/executor.rs:143]: Done in 4e6fec6
